# Generated by Django 3.1 on 2021-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
