# Generated by Django 3.1 on 2021-04-06 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=1000)),
                ('alarm', models.CharField(max_length=1000)),
                ('opened', models.CharField(max_length=1000)),
                ('ticket', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alarm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlarmComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=5000)),
                ('original_alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.alarm')),
                ('user_comm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alarm_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlarmArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arcv_site_name', models.CharField(max_length=5000)),
                ('arcv_alarm', models.CharField(max_length=5000)),
                ('arcv_alarm_opened', models.CharField(max_length=5000)),
                ('arcv_ticket', models.CharField(max_length=255)),
                ('all_comments', models.CharField(max_length=25000)),
                ('time_stamp', models.DateField(auto_now_add=True)),
                ('user_close', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alarm_archive',
                'managed': True,
            },
        ),
    ]
