# Generated by Django 3.0 on 2020-12-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_identity', models.CharField(max_length=50)),
                ('alarm', models.CharField(max_length=255)),
                ('alarm_date', models.CharField(max_length=255)),
                ('ticket_closed', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'alarm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlarmArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arcv_site_name', models.CharField(max_length=50)),
                ('arcv_site_identity', models.CharField(max_length=50)),
                ('arcv_alarm', models.CharField(max_length=255)),
                ('arcv_alarm_date', models.CharField(max_length=255)),
                ('arcv_ticket_closed', models.BooleanField(default=False)),
                ('all_comments', models.CharField(max_length=2000)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'alarm_archive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlarmComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('comments', models.CharField(max_length=250)),
                ('original_alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.Alarm')),
            ],
            options={
                'db_table': 'alarmtrace',
                'managed': True,
            },
        ),
    ]
