# Generated by Django 3.1 on 2021-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketno', models.CharField(max_length=25, unique=True)),
                ('site_loc', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ticketlog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceTicketArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketno', models.CharField(max_length=25, unique=True)),
                ('site_loc', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ticketlogarchive',
                'managed': True,
            },
        ),
    ]
