"""
Django settings for devproj project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import json
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.isics.info','isics.info']


# Application definition

INSTALLED_APPS = [
    'alarm.apps.AlarmConfig',
    'base.apps.BaseConfig',
    'generator.apps.GeneratorConfig',
    'isicsapplicant.apps.IsicsapplicantConfig',
    'pointofcontact.apps.PointofcontactConfig',
    'servicecall.apps.ServicecallConfig',
    'sitemaintenance.apps.SitemaintenanceConfig',
    'suggestion.apps.SuggestionConfig',
    'ticketsystem.apps.TicketsystemConfig',
    'towersite.apps.TowersiteConfig',
    'notam.apps.NotamConfig',
    'user.apps.UserConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'devproj.middleware.SessionIdleTimeout',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'devproj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DEVELOPMENT DATABASE CONNECTION

SHENANIGANS = None
with open(os.path.join(BASE_DIR, 'devproj/app-config.json')) as f:
    # The next person that says shenanigans
    SHENANIGANS = json.load(f)
    # Ohhhhhhhhh

SECRET_KEY = SHENANIGANS['SKK']

#DATABASES = {
#   'default': {
#       'ENGINE': 'django.db.backends.postgresql_psycopg2',
#       'NAME': 'Interoperability',
#       'USER': 'Administrator',
#       'PASSWORD': '@ISPtech918#',
#       'HOST': 'localhost',
#       'PORT': '5432',
#   }
#}
DATABASES = {
    'default': {
    'ENGINE': SHENANIGANS['DATABASE_ENGINE'],
    'NAME': SHENANIGANS['DATABASE_NAME'],
    'USER': SHENANIGANS['DATABASE_USER'],
    'PASSWORD': SHENANIGANS['DATABASE_PASSWORD'],
    'HOST': SHENANIGANS['DATABASE_HOST'],
    'PORT': SHENANIGANS['DATABASE_PORT'],
     }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
     'django.contrib.auth.backends.ModelBackend'
]

# Development
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production
# EMAIL_BACKEND = 'django_ses.SESBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = SHENANIGANS['EMAIL_HOST']
EMAIL_PORT = SHENANIGANS['EMAIL_PORT']
EMAIL_HOST_USER = SHENANIGANS['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = SHENANIGANS['EMAIL_HOST_PASSWORD']
EMAIL_USE_TLS = SHENANIGANS['EMAIL_USE_TLS']


DEFAULT_FROM_EMAIL = SHENANIGANS['DEFAULT_FROM_EMAIL']

AWS_ACCESS_KEY_ID = SHENANIGANS['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = SHENANIGANS['AWS_SECRET_ACCESS_KEY']


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Logout after a period of inactivity
INACTIVE_TIME = 30*60  # 15 minutes - or whatever period you think appropriate
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE= True
SESSION_COOKIE_AGE = INACTIVE_TIME   # change expired session
SESSION_IDLE_TIMEOUT = INACTIVE_TIME  # logout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#CSRF_COOKIE_DOMAIN = ".isics.info"
##SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDER_PROTO","https")
#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

### MAKE SURE TO CORRECT BEFORE LOGIN PAGE

LOGIN_REDIRECT_URL = 'base:home-page' # Go to index homepage after successful login
LOGIN_URL = 'base:login'  # Redirects to Login Screen home page
