# Generated by Django 3.0 on 2021-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notam',
                'managed': True,
            },
        ),
    ]
