# Generated by Django 3.1 on 2021-03-08 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='NotamArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notam_archive',
                'managed': True,
            },
        ),
    ]
